---

- name: Install Common Attributes
  hosts: all
  remote_user: vagrant
  sudo: yes
  roles:
        - common

- name: Install And Configure Nginx
  hosts: nginx
  remote_user: vagrant
  sudo: yes
  roles:
        - nginx

- name: Install And Configure MySQL
  hosts: mysql
  remote_user: vagrant
  sudo: yes
  roles:
        - mysql

- name: Install PHP-FPM And Deploy The PHP Code
  hosts: phpfpm
  remote_user: vagrant
  sudo: yes
  roles:
        - phpfpm
